#!/bin/bash

function read_dir() {
	for file in `ls $1`
	do
		if [ -d $1"/"$file ]
		then
			read_dir $1"/"$file
		else
			echo $1"/"$file
		fi
	done
}

if [[ ! -z $1 ]]
then
	case $1 in
	-f)
		if [ ! -z $2 ]
		then
			for i in `ls`
			do
				if [ $i = $2 ]
				then
					echo "find the file or dictionary!"
					exit
				fi
			done
			echo "there are no file or dictionary named $2"
		else echo "option error, the '-f' has option!"
		fi
		;;
	*) echo "option error, please input the current option!"
	esac
else
	path=`pwd`
	echo "the root path is: $path"
	echo "the listing of all files is:"
	read_dir $path
	echo
fi
